upgrading_to_fusion:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "BVTBGRH-VF24119"

      user: "CARLOSPERALES"
      password: "Pascualfuncion@7" # enter password you used to signup for Snowflake demo account here
      role: ACCOUNTADMIN
      
      database: snowflake_learning_db
      warehouse: compute_wh
      schema: dbt_cperales
    fusion_dev:
      type: snowflake
      account: "BVTBGRH-VF24119"

      user: "CARLOSPERALES"
      password: "Pascualfuncion@7" # enter password you used to signup for Snowflake demo account here
      role: ACCOUNTADMIN
      
      database: snowflake_learning_db
      warehouse: compute_wh
      schema: fusion_dev
